### ISSUE TITLE
Add  Codecov for coverage reporting

### ISSUE THREAD

**Issue by eonist** [sentryco/Dice#6]
To add unit test coverage to a GitHub repository with Swift code for a Swift package, follow these steps:

1. Enable code coverage in your Xcode scheme by selecting "Edit Scheme" > "Test" and checking "Gather coverage" for your target[1].

2. Create a GitHub Actions workflow file in your repository's `.github/workflows` directory with the following content:

```yaml
name: Test Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Package
        run: swift build -v

      - name: Run tests with coverage
        run: swift test --enable-code-coverage

      - name: Generate coverage report
        run: xcrun llvm-cov export -format="lcov" .build/debug/<YourPackageName>PackageTests.xctest/Contents/MacOS/<YourPackageName>PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.lcov
```

This workflow will run your tests with code coverage enabled and generate a coverage report[2].

3. Add a Codecov token to your GitHub repository secrets if you want to use Codecov for coverage reporting[2].

4. To view the coverage results locally, you can use the Report navigator in Xcode after running the tests[5].

5. If you encounter issues with macros or plugin dependencies, you may need to investigate further, as there have been reports of undefined symbols when building with coverage for packages using macros[3].

6. To display the coverage badge in your README.md, add the following markdown:

```markdown
[![codecov](https://codecov.io/gh/<username>/<repository>/branch/main/graph/badge.svg)](https://codecov.io/gh/<username>/<repository>)
```

By following these steps, you'll have unit test coverage integrated into your GitHub repository for your Swift package, providing visibility into your test coverage and helping maintain code quality.

Citations:
[1] https://bitrise.io/blog/post/code-coverage-for-swift-package-manager-based-apps
[2] https://thisdevbrain.com/swift-packages-and-github-actions/
[3] https://forums.swift.org/t/testing-code-coverage-when-using-macros/65838
[4] https://community.sonarsource.com/t/example-code-coverage-setup-for-swift-and-github-actions/103763
[5] https://stackoverflow.com/questions/72027806/how-do-i-show-code-coverage-in-swift-packages
[6] https://brightdigit.com/tutorials/swift-package-continuous-integration-guide/
[7] https://forums.developer.apple.com/forums/thread/710374
[8] https://about.codecov.io/language/swift/
